name: Update submodule

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  updateSubmodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'swift-5.7.2-RELEASE'

      - name: Set Git config
        run: |
          git config user.name 'Submodule AutoUpdater'
          git config user.email 'actions@users.noreply.github.com'

      - name: Update submodule
        id: upsb
        run: |
          git submodule update --init
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi

      - name: Push changes
        if: ${{ steps.upsb.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: swift-5.7.2-RELEASE

 